const characters = {
	dc_shen_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dccangming", "dcchouxi", "dcjichao"],
		groupInGuozhan: "wu",
	},
	shen_zhonghui: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dclinjie", "dcduzhang", "dcjianghuo"],
		groupInGuozhan: "ye",
		clans: ["颍川钟氏"],
	},
	shen_pangtong: {
		sex: "male",
		group: "shen",
		hp: 1,
		maxHp: 1,
		skills: ["luansuo", "fengliao", "kunyu"],
		groupInGuozhan: "shu",
	},
	junk_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["yizhao", "junksijun", "tianjie"],
		groupInGuozhan: "qun",
		dieAudios: ["shen_zhangjiao"],
	},
	shen_huangzhong: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["new_dclieqiong", "dczhanjue"],
		groupInGuozhan: "shu",
	},
	xin_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["xinrenjie", "xinbaiyin", "xinlianpo"],
		tempname: ["new_simayi"],
		groupInGuozhan: "wei",
		names: "司马|懿",
		dieAudios: ["new_simayi"],
	},
	dc_shen_huatuo: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["jingyu", "lvxin", "huandao"],
		groupInGuozhan: "qun",
	},
	shen_xuzhu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["zhengqing", "zhuangpo"],
		groupInGuozhan: "wei",
	},
	le_shen_jiaxu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["jxlianpo", "jxzhaoluan"],
		groupInGuozhan: "qun",
	},
	shen_dianwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["juanjia", "qiexie", "cuijue"],
		groupInGuozhan: "wei",
	},
	shen_dengai: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["dctuoyu", "dcxianjin", "dcqijing"],
		groupInGuozhan: "wei",
	},
	tw_shen_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["twshelie", "twgongxin"],
		groupInGuozhan: "wu",
		dieAudios: ["shen_lvmeng"],
	},
	shen_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["yizhao", "sijun", "sanshou", "tianjie"],
		groupInGuozhan: "qun",
	},
	shen_zhangfei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["shencai", "xunshi"],
		groupInGuozhan: "shu",
	},
	tw_shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["twwushen", "twwuhun"],
		groupInGuozhan: "shu",
	},
	shen_machao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["shouli", "hengwu"],
		groupInGuozhan: "shu",
	},
	shen_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["junkyuheng", "junkdili"],
		groupInGuozhan: "wu",
	},
	shen_jiangwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["jiufa", "tianren", "pingxiang"],
		groupInGuozhan: "shu",
	},
	shen_guanyu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["wushen", "new_wuhun"],
		groupInGuozhan: "shu",
	},
	shen_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 2,
		skills: ["xinjuejing", "relonghun"],
		groupInGuozhan: "shu",
	},
	shen_zhugeliang: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["qixing", "kuangfeng", "dawu"],
		groupInGuozhan: "shu",
		names: "诸葛|亮",
	},
	shen_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["shelie", "gongxin"],
		groupInGuozhan: "wu",
	},
	shen_zhouyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["yeyan", "qinyin"],
		groupInGuozhan: "wu",
	},
	shen_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["renjie", "sbaiyin", "lianpo"],
		groupInGuozhan: "wei",
		names: "司马|懿",
	},
	shen_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["new_guixin", "feiying"],
		groupInGuozhan: "wei",
	},
	shen_lvbu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["baonu", "wumou", "ol_wuqian", "ol_shenfen"],
		groupInGuozhan: "qun",
	},

	shen_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["nzry_longnu", "nzry_jieying"],
		groupInGuozhan: "shu",
	},
	shen_luxun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["nzry_junlve", "nzry_cuike", "nzry_dinghuo"],
		groupInGuozhan: "wu",
		clans: ["吴郡陆氏"],
	},
	shen_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["drlt_duorui", "drlt_zhiti"],
		groupInGuozhan: "wei",
	},
	shen_ganning: {
		sex: "male",
		group: "shen",
		hp: 3,
		maxHp: 6,
		skills: ["drlt_poxi", "drlt_jieying"],
		groupInGuozhan: "wu",
	},
	ol_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["olduorui", "olzhiti"],
		groupInGuozhan: "wei",
		dieAudios: ["shen_zhangliao"],
	},
	shen_caopi: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["chuyuan", "dengji"],
		groupInGuozhan: "wei",
	},
	shen_zhenji: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["shenfu", "qixian"],
		groupInGuozhan: "wei",
	},
};

export default characters;
